---
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host #optional
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Etc/UTC #optional
      - SUBDOMAINS=devboer
      - TOKEN=cc0492a0-9d6d-4f10-9e4d-a95a79f3c325
      - UPDATE_IP=ipv4 #optional
      - LOG_FILE=false #optional
    volumes:
      - /mnt/data/docker/duckdns:/config #optional
    restart: unless-stopped
